# Generated by Django 3.1 on 2020-08-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200826_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
