# Generated by Django 3.1 on 2020-08-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepageslider_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageslider',
            name='alt',
        ),
    ]
