# Generated by Django 3.1 on 2020-08-27 10:36

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200827_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default='Test'),
            preserve_default=False,
        ),
    ]
