# Generated by Django 3.1 on 2020-08-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slider_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
