# Generated by Django 3.1 on 2020-08-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_slider_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='slider_title',
        ),
    ]
