# Generated by Django 3.1 on 2020-08-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepage_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slider_title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
